### ISSUE TITLE
Hi from APIs.guru :)

### ISSUE THREAD

**Issue by IvanGoncharov** [jdecked/apicrawler#1]
@jdecked Thank you for using my project.
I use [this](https://github.com/search?o=desc&q=%22apis.guru%22+-user%3AAPIs-guru+-user%3AAPIs-guru-obsolete+-user%3Abobby-brennan+-user%3Alucybot+-user%3ARebilly&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93) query to find all repos mentioning APIs.guru, that's how I found your project :smile: 

I saw that you parsing HTML list of API hosted here:
https://apis-guru.github.io/api-models/
I actually have [API](https://github.com/APIs-guru/api-models/blob/master/API.md) for move easy access, please take a look at this file:
https://apis-guru.github.io/api-models/api/v1/list.json

If you have any questions you can ask me directly through Skype(ivangon4arov), Hangout(ivan.goncharov.ua@gmail.com) or you can ask them in [Gitter chat](https://gitter.im/APIs-guru/api-models).

**Comment by jdecked** [comment]
Hey Ivan! Thanks for your email and the pointer to the API :) it definitely
is more easy access, but I'd written this as an interview question for a
company that wanted me to parse the YAML specifically + crawl the links.
Super useful project, especially the JSON version — thanks for building it!

**Comment by IvanGoncharov** [comment]
I'm very intrigued to say the least.
I will understand if you can't answer due to NDA or something similar.
But I need to ask these questions or I will not sleep tonight :smile: 

So they asked you to parse APIs.guru?
Or you just use my project as an example?

**Comment by jdecked** [comment]
Specifically asked to parse APIs.guru, for some of the building blocks of a
new part of their project. The company, if you were wondering, is called
Paw (luckymarmot.com/paw), but I don't think I should say more than that :)

**Comment by IvanGoncharov** [comment]
@jdecked Thanks a lot. I spoke with founder of this company few months ago.
I need to learn how to keep in touch with community :disappointed:
